name: 'Exec php-ast'
description: 'phpファイル'
inputs:
  main-branch:
    description: 'default branch name'
    required: true
    default: 'main'
runs:
    using: 'composite'
    steps:
      - run: $GITHUB_ACTION_PATH/test.sh
        shell: bash
