on: [push]

jobs:
    php_ast_job:
    runs-on: ubuntu-18.04
    name: PHP Ast
    steps:
    - name: Exec
        id: php-ast-action
        uses: fan-ADN/php-ast-action@v20.10.4
        with:
            main-branch: 'master'

    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: fan-ADN/php-ast-action@v20.10.3
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"